// import { z } from 'zod';
// import { InsertProductSchema } from '@/lib/validators';
 import { Decimal } from '@prisma/client/runtime/library';
 export type Product = {
    id: string;
    name: string;
    slug: string;
    category: string;
    brand: string;
    description: string;
    stock: number;
    images: string[];
    isFeatured: boolean;
    banner: string | null;
    price: Decimal;
    rating: Decimal;
    numReviews: number;
    createdAt: Date;
    updatedAt: Date;
  };